# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# Mod properties
mod_id = gleam
mod_name = Gleam
mod_license = CC BY-NC-ND 4.0
mod_version = 1.1.0.0
mod_group_id = net.thatmaidenjaden.gleam
mod_authors = ThatJadenXgamer (ThatMaidenJaden)
mod_description = Gleam is a powerful and very customizable colored lights mod that can render many lights at very high distances with an incredible amount of optimization compared to others of its kind.

# Minecraft properties
minecraft_version = 1.21.1
minecraft_version_range = [1.21.1]

# Parchment properties
parchment_minecraft_version = 1.21.1
parchment_mappings_version = 2024.11.17

# Fabric properties
fabric_loader_version = 0.19.5
fabric_api_version = 0.116.17+1.21.1

# dependencies
lodestone_version = 1.21.1-1.8.2.525
curios_version = 9.5.1+1.21.1
modmenu_version = 11.0.4
cloth_config_version = 15.0.140
yacl_version = 3.8.2+1.21.1-fabric