# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# Mod properties
mod_id = gleam
mod_name = Gleam
mod_license = CC BY-NC-ND 4.0
mod_version = 1.0.0
mod_group_id = net.thatmaidenjaden.gleam
mod_authors = ThatJadenXgamer (ThatMaidenJaden)
mod_description = Gleam is a powerful and customizable colored lights mod that can render many lights at very high distances with little to no FPS drawbacks due to incredible amounts of optimization compared to others of its kind.

# Minecraft properties
minecraft_version = 1.21.1
minecraft_version_range = [1.21.1]

# Parchment properties
parchment_minecraft_version = 1.21.1
parchment_mappings_version = 2024.11.17

# NeoForge properties
neoforge_version = 21.1.230
loader_version_range=[1,)

# dependencies
lodestone_version = 1.21.1-1.8.2.525
curios_version = 9.5.1+1.21.1